# Generated by Django 3.1.7 on 2021-05-06 18:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id_about', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.TextField(blank=True, max_length=10000, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about_us')),
            ],
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id_announcement', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, max_length=10000, null=True)),
                ('submited_date', models.DateTimeField(default=datetime.datetime(2021, 5, 6, 21, 50, 47, 76287))),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='daysClosed',
            fields=[
                ('id_day', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id_exercise', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msfitcaregym.categories')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id_package', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('special_offer', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysioPrices',
            fields=[
                ('id_package', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='repeatingDaysClosed',
            fields=[
                ('id_day', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, max_length=200, null=True)),
                ('total_persons', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id_day', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, choices=[('Αύξηση Βάρους', 'Αύξηση Βάρους'), ('Υγεία', 'Υγεία'), ('Αποκατάσταση Τραυματισμών', 'Αποκατάσταση Τραυματισμών'), ('Συντήρηση', 'Συντήρηση'), ('Μείωση Βάρους', 'Μύωση Βάρους')], max_length=100, null=True)),
                ('first_time_gym', models.BooleanField(blank=True, null=True)),
                ('smoking', models.BooleanField(blank=True, null=True)),
                ('surgery', models.CharField(blank=True, max_length=300, null=True)),
                ('heart_problems', models.CharField(blank=True, max_length=300, null=True)),
                ('medicines', models.CharField(blank=True, max_length=300, null=True)),
                ('normal_blood_test', models.BooleanField(blank=True, null=True)),
                ('cardiac_test', models.BooleanField(blank=True, null=True)),
                ('epilepsy', models.CharField(blank=True, max_length=200, null=True)),
                ('headache', models.CharField(blank=True, max_length=200, null=True)),
                ('myosceletical_problems', models.CharField(blank=True, max_length=300, null=True)),
                ('other_problems', models.CharField(blank=True, max_length=300, null=True)),
                ('stable_weight', models.BooleanField(blank=True, null=True)),
                ('approve', models.BooleanField(blank=True, null=True)),
                ('accountStatus', models.CharField(choices=[('Request', 'Request'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Revoke', 'Revoke'), ('NoUser', 'NoUser')], default='Request', max_length=30)),
                ('checkann', models.DateTimeField(blank=True, null=True)),
                ('package_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msfitcaregym.packages')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id_slot', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msfitcaregym.type')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramUser',
            fields=[
                ('id_program', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, default=datetime.date(2021, 5, 6), null=True)),
                ('goal', models.CharField(choices=[('Μύωση Βάρους', 'Μύωση Βάρους'), ('Αύξηση Βάρους', 'Αύξηση Βάρους'), ('Υγεία', 'Υγεία'), ('Αποκατάσταση Τραυματισμών', 'Αποκατάσταση Τραυματισμών'), ('Συντήρηση', 'Συντήρηση')], max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msfitcaregym.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDates',
            fields=[
                ('id_program_date', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, choices=[('Μέρα 4', 'Μέρα 4'), ('Μέρα 2', 'Μέρα 2'), ('Μέρα 5', 'Μέρα 5'), ('Μέρα 6', 'Μέρα 6'), ('Μέρα 3', 'Μέρα 3'), ('Μέρα 1', 'Μέρα 1')], max_length=200, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msfitcaregym.programuser')),
            ],
        ),
        migrations.CreateModel(
            name='PhysioReservations',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('cancel', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msfitcaregym.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PhysioCard',
            fields=[
                ('id_card', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msfitcaregym.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id_payment', models.AutoField(primary_key=True, serialize=False)),
                ('pay_from', models.DateField(blank=True, null=True)),
                ('pay_until', models.DateField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msfitcaregym.packages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msfitcaregym.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GymReservations',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('attendance', models.BooleanField(default=True)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msfitcaregym.slots')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msfitcaregym.type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msfitcaregym.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id_gallery', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('details', models.TextField(blank=True, max_length=10000, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msfitcaregym.type')),
            ],
        ),
        migrations.CreateModel(
            name='ExercisesPerDate',
            fields=[
                ('id_exercises_date', models.AutoField(primary_key=True, serialize=False)),
                ('sets', models.PositiveIntegerField(blank=True, null=True)),
                ('times', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, default='#000000', max_length=100, null=True)),
                ('negative', models.BooleanField(blank=True, default=False, null=True)),
                ('id_exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msfitcaregym.exercises')),
                ('id_program_Date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msfitcaregym.programdates')),
            ],
        ),
        migrations.CreateModel(
            name='BodyParts',
            fields=[
                ('id_part', models.AutoField(primary_key=True, serialize=False)),
                ('circle_id', models.CharField(blank=True, max_length=500, null=True)),
                ('partid', models.CharField(blank=True, max_length=500, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=500, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('physio_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msfitcaregym.physiocard')),
            ],
        ),
    ]
